# Generated by Django 4.0.1 on 2022-01-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
