# Generated by Django 4.0.1 on 2022-01-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lista',
            new_name='Produto',
        ),
    ]
