# Generated by Django 4.0.1 on 2022-01-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco por unidade'),
        ),
    ]
